# Generated by Django 2.0 on 2017-12-22 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('em_processo', 'Em Processo'), ('processado', 'Processado'), ('falhou', 'Falhou')], max_length=100)),
            ],
        ),
    ]
