# Generated by Django 2.0 on 2017-12-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('em_processo', 'Em Processo'), ('processado', 'Processado'), ('falhou', 'Falhou')], default='novo', max_length=100),
        ),
    ]
