# Generated by Django 2.0 on 2017-12-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_auto_20171222_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='fui',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='email',
            name='resultado',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
